# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField(max_length=100)),
                ('age', models.IntegerField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('number', models.IntegerField(max_length=11)),
                ('profession', models.CharField(max_length=600)),
                ('hobbies', models.CharField(max_length=600)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
