# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20171022_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
